version: '3'
services:
  db:
    image: postgres:15
    container_name: hr_bank-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hr_bank
      POSTGRES_USER: team01_username
      POSTGRES_PASSWORD: team01_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
