spring:
  datasource:
    # PostgreSQL JDBC URL (이미지에 나온 정보 기반)
    url: jdbc:postgresql://localhost:5432/hr_bank
    # 데이터베이스 사용자 이름 (이미지에 나온 정보 기반)
    username: team01_username
    # 데이터베이스 비밀번호 (사용자가 제공한 정보)
    password: team01_password
    # PostgreSQL 드라이버 클래스 이름
    driver-class-name: org.postgresql.Driver이버 클래스 이름 (보통 자동 감지되지만 명시해도 좋음)


  # --- 이하 다른 설정들은 그대로 유지 ---
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  backup:
    schedule:
      time: "0 0 * * * *" # 한 시간마다

  task:
    scheduling:
      pool:
        size: 2
