
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr_bank
    username: team01_username
    password: team01_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  backup:
    schedule:
      time:  "0 0 * * * *"
  task:
    scheduling:
      pool:
        size: 2

