server:
  port: 7999

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr_bank
    username: team01_username
    password: team01_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  backup:
   schedule:
     time: "0 0 * * * *" # 한 시간마다

  task:
   scheduling:
     pool:
      size: 2
